landmarks:
  - id: 0
    x: 0.0
    y: 0.0
  - id: 1
    x: 7.31
    y: 0.0
  - id: 2
    x: 7.19
    y: 7.55
  - id: 15
    x: 7.63
    y: 13.24
  - id: 9
    x: 14.77
    y: 6.89
  - id: 6
    x: 21.01
    y: 13.21
  - id: 7
    x: 20.96
    y: 3.36
  - id: 12
    x: 29.92
    y: 11.44
  - id: 4
    x: 33.77
    y: 6.41
  - id: 13
    x: 32.79
    y: -6.79
  - id: 3
    x: 18.85
    y: -3.59
  - id: 10
    x: 22.46
    y: -10.36
  - id: 11
    x: 31.56
    y: -18.81
  - id: 8
    x: 20.40
    y: -19.41
  - id: 5
    x: 13.22
    y: -13.61
  - id: 14
    x: 2.04
    y: -12.02
